ARG FULL_TAG=latest
FROM --platform=$TARGETPLATFORM apluslms/grade-python:$FULL_TAG

RUN apt_install \
    bc \
    python3-tk \
 && pip_install \
# Excel file parser is useful with pandas
    openpyxl \
    xlrd \
    xlwt \
    bokeh==2.3.3 \
    iapws \
    pixelmatch \
    "matplotlib >= 3.5.0" \
    "scipy >= 1.12.0" \
    "numpy == 1.23.5" \
    "Pillow >= 9.0.0" \
 && :
